### ISSUE TITLE
Brazil and daylight savings

### ISSUE THREAD

**Issue by luckyx1** [tzinfo/tzinfo#105] opened 2019-11-07 21:17 UTC
Now that Brazil is declaring the end of daylight savings, do we need to make any changes to the gem to accommodate this change? https://time.is/time_zone_news/no_dst_in_brazil_in_2019

**Comment by philr** [comment] 2019-11-07 22:16
Duplicate of #102  

See also #104 if you are using TZInfo 0.3.x.

**Comment by philr** [comment] 2019-11-07 22:16
See also #104 if you are using TZInfo 0.3.x.

**Closed by philr** 2019-11-07 22:16 UTC

**Comment by luckyx1** [comment] 2019-11-07 22:33
Thanks so much!
