### ISSUE TITLE
*** TZInfo::InvalidTimezoneIdentifier Exception: Invalid identifier

### ISSUE THREAD

**Issue by bilicheng** [tzinfo/tzinfo#126] opened 2021-05-06 09:11 UTC
There is an error on the following list:
LHDT | Lord Howe Daylight Time | Australia | UTC +11
LHST | Lord Howe Standard Time | Australia | UTC +10:30
NFDT | Norfolk Daylight Time |   | UTC 
NFT | Norfolk Time |   | UTC +11

**Comment by philr** [comment] 2021-05-06 19:02
You've not posted enough to work out what the issue is here.

The [`TZInfo::InvalidTimezoneIdentifier`](https://rubydoc.info/gems/tzinfo/TZInfo/InvalidTimezoneIdentifier) exception will be raised if an unrecognized time zone identifier is passed to TZInfo. The identifier has to be one that's found in your configured data source (i.e. either your system zoneinfo directory or the tzinfo-data gem). You can use [`TZinfo::Timezone.all_identifiers`](https://rubydoc.info/gems/tzinfo/TZInfo%2FTimezone%2Eall_identifiers) to get a list of recognized time zone identifiers.

I'm closing this for now. Please reopen if you can explain what the issue with TZInfo is (ideally with some code, version numbers, etc)?

**Closed by philr** 2021-05-06 19:02 UTC

**Comment by kingdonb** [comment] 2022-11-05 20:16
I had this issue myself, I was using `my_zone = Time.now.getlocal.zone` to get the local time zone, which sometimes returns `'EDT'` that does not appear in `TZInfo::Timezone.all_identifiers`, and then trying to use it to get the current date as explicitly as I can do in the local time zone, as in:

```
DateTime.parse(selected_date).in_time_zone( my_zone ).to_date
```

I wasn't able to find a good way to solve that, in the commit I just pushed that referenced this issue you can see what I wound up doing (which is horrible, but my code won't be running in any other time zones as far as I know, so I guess it's OK)
