### ISSUE TITLE
Could not find gem 'tzinfo (~> 1.2)' in locally installed gems.

### ISSUE THREAD

**Issue by MahmoudMuhammedAli** [tzinfo/tzinfo#127] opened 2021-11-11 18:52 UTC
I have installed all `"tzinfo", "~> 1.2"` and yet I still get this error.

![Screenshot 2021-11-11 204959](https://user-images.githubusercontent.com/70591959/141352936-bffbfcdc-5324-4c3a-aa08-3e1e58686714.png)

**Comment by philr** [comment] 2021-11-11 19:07
Have you tried running `bundle install` as the error suggests?

This is a problem with your Jekyll setup and not an issue with tzinfo. I'd therefore suggest posting a question on [Jekyll Talk](https://talk.jekyllrb.com).

I'm closing this as a duplicate of #115.

**Closed by philr** 2021-11-11 19:07 UTC

**Comment by MahmoudMuhammedAli** [comment] 2021-11-11 19:17
I tried running `bundle install` and it gives me this error
```
An error occurred while installing http_parser.rb (0.6.0), and Bundler cannot
continue
```
I tried the solution from #115  and it didn't work for me.

**Comment by philr** [comment] 2021-11-11 19:24
http_parser.rb is a (recursive) dependency of Jekyll (and unrelated to tzinfo). I'd look at solving that issue first.
