### ISSUE TITLE
dst? returns true for Europe/Dublin during winter time

### ISSUE THREAD

**Issue by MohammedAbuissa** [tzinfo/tzinfo#107] opened 2019-11-13 12:07 UTC
Steps to reproduce
```
irb(main):010:0> require 'tzinfo'
=> false
irb(main):011:0> Gem.loaded_specs["tzinfo"].version
=> #<Gem::Version "2.0.0">
irb(main):012:0> tz = TZInfo::Timezone.get('Europe/Dublin')
=> #<TZInfo::DataTimezone: Europe/Dublin>
irb(main):013:0> local_time = tz.local_time(2019, 11, 13, 12, 30)
=> 2019-11-13 12:30:00 +0000
irb(main):017:0> local_time.dst?
=> true
irb(main):014:0> local_time = tz.local_time(2019, 8, 13, 12, 30)
=> 2019-08-13 12:30:00 +0100
irb(main):015:0> local_time.dst?
=> false
```

The DST is kind of flipped and don't match https://www.timeanddate.com/time/change/ireland/dublin description where is says DST has ended on 27th of Oct 2019.

Can anyone explain why is DST flipped?

**Comment by philr** [comment] 2019-11-13 20:08
Duplicate of #95

**Closed by philr** 2019-11-13 20:08 UTC
